### ISSUE TITLE
Bad ratio L/H handling 

### ISSUE THREAD

**Issue by vieilfrance** [lagaisse/BrokenStuff#5]
When adding a new report, the ratio H/L of the image added is not the same on desktop and on mobile.
Consequence : the thumbnails displayed for each search results is improper

**Comment by vieilfrance** [comment]
Corrigé dans le commit d3265f812b2806cdc4344b13618b380a48af1abd
Cela ne corrige, cependant, pas les précédent report puisque le ratio d'origine n'est pas bon.

**Comment by lagaisse** [comment]
Ca déconne toujours

**Comment by lagaisse** [comment]
https://wasabite.slack.com/archives/brokenstuff/p1437396766000004

**Comment by vieilfrance** [comment]
C'est re corrigé ^^ 7db5e134c87bfd0308bb4e3b71b55880fbfda7ca
