### ISSUE TITLE
Affichage de la zone de l'image du report pas aux dimensions de l'image

### ISSUE THREAD

**Issue by lagaisse** [lagaisse/BrokenStuff#6]
la zone permettant l'ajout d'un image dans le formulaire de saisie est plus petite que la zone d'affichage de l'image dans la consultation du report en hauteur.

cf http://bs.lagaisse.fr/#/report/23

ps de pb au niveau de la recherche.

lié à #5

**Comment by vieilfrance** [comment]
Corrigé avec le commit d3265f812b2806cdc4344b13618b380a48af1abd 
Une hauteur à 100% mal placée que j'ai enlever lorsqu'on est en mode édition d'un report.
